#include <gtest/gtest.h>
#include "Drivers/InvIMU/fifo_clock.hpp"

using Drivers::InvIMU::FifoClock;

TEST(FifoClock, AgesCappedOldestBurstRatherThanAnchoringItToNow) {
  FifoClock c;
  auto b = c.map(1000, 16781, 15781, 297, 1000000);
  EXPECT_NEAR(b.first_us, 1000000 - 297.5 * 156.25 - 15781, 1);
}

TEST(FifoClock, AdjacentCounterWrapPreservesSpacing) {
  FifoClock c;
  auto a = c.map(65000, 65000, 0, 1, 1000000);
  auto b = c.map(656, 656, 0, 1, 1001200);
  EXPECT_NEAR(b.first_us - a.first_us, 1192, 2);
  EXPECT_EQ(c.recoveredWraps(), 0u);
}

TEST(FifoClock, RecoversMultipleMissingWrapsAfterAStall) {
  FifoClock c;
  auto a = c.map(1000, 1000, 0, 1, 1000000);
  auto b = c.map(static_cast<uint16_t>(151000), static_cast<uint16_t>(151000),
                 0, 1, 1150000);
  EXPECT_NEAR(b.first_us - a.first_us, 150000, 2);
  EXPECT_EQ(c.recoveredWraps(), 2u);
  EXPECT_EQ(c.reacquisitions(), 1u);
}

TEST(FifoClock, TracksOscillatorRateAndPollingPhaseWithoutTimeReversal) {
  for (float actual_tick_us : {0.994f, 1.006f}) {
    FifoClock c;
    uint64_t previous_end = 0;
    uint32_t raw = 10000;
    int64_t max_error = 0;
    for (unsigned i = 0; i < 3000; ++i) {
      // 64-sample bursts; alternate register-read polling phase, plus capped
      // bursts during initial backlog. Time is generated by an independent
      // host clock, not by the mapper's oscillator estimate.
      const uint32_t first = raw;
      const uint32_t span = 9844;
      const uint16_t unread = i < 10 ? 297 : 1;
      const uint64_t true_end = 1000000 + static_cast<uint64_t>((raw + span) * actual_tick_us);
      const uint64_t read_time = true_end + static_cast<uint64_t>(
          (unread + (i % 2 ? 0.2f : 0.8f)) * 156.25f * actual_tick_us);
      auto b = c.map(static_cast<uint16_t>(first), static_cast<uint16_t>(raw + span),
                     span, unread, read_time);
      EXPECT_GT(b.first_us, previous_end);
      previous_end = b.first_us + static_cast<uint64_t>(span * b.tick_us + 0.5f);
      if (i > 100) max_error = std::max<int64_t>(max_error,
          std::abs(static_cast<int64_t>(previous_end) - static_cast<int64_t>(true_end)));
      raw += 10000;
    }
    EXPECT_LT(max_error, 120);
    EXPECT_NEAR(c.scalePpm(), (actual_tick_us - 1) * 1e6f, 500);
    EXPECT_EQ(c.recoveredWraps(), 0u);
  }
}
